name: Rust

on:
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Check
        run: cargo check -v
      - name: Code style
        run: cargo clippy -v
      - name: Run tests
        run: cargo test --verbose
