name: Anguila CI final

on:
  push:
    branches:
      - 'master'
      - 'ci'

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: ~/.cargo

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: rust:1.69.0

    steps:
      - name: Cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo
            /root/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: apt-get update && apt-get install -y libasound2-dev libudev-dev

      - name: Install components
        run: rustup component add clippy rustfmt

      - name: Get version
        run: export app_version=$(cat Cargo.toml | grep version | cut -d '"' -f2)

      - name: Code style
        run: cargo clippy
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --release
      
      - name: Prepare artifacts
        run: "mkdir /release -vp && mv -v target/release/anguila /release/anguila-$app_version"
      
      - name: Tar artifacts
        run: tar -cvf /release.tar /release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
         name: "anguila"
         path: /release.tar
         retention-days: 30

