name: Rust CI a

on:
  push:
    branches:
      - 'master'
      - 'ci'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: rust:1.69.0
      env:
        CARGO_HOME: /.cargo

    steps:
      - name: Cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: apt-get update && apt-get install -y libasound2-dev libudev-dev

      - name: Install components
        run: rustup component add clippy rustfmt

      - name: Get version
        run: app_version=$(cat Cargo.toml | grep version | cut -d '"' -f2)

      - name: Code style
        run: cargo clippy
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
         name: "anguila-$app_version"
         path: target/release/anguila

